#!/bin/env bash

KATANA_REPO="Apps/Katana"
KATANA_OBJECTS="$KATANA_REPO/objects"

function initTmux {
    tmux new-session -s $1 -n console -d
    tmux send-keys -t $1 "cd $2" C-m
    tmux send-keys -t $1 "clear" C-m
}

function setWindows {
    # Git window
    tmux new-window -n git -t $1
    tmux split-window -t $1:1
    tmux send-keys -t $1:1.0 "cd $2/$KATANA_REPO" C-m
    tmux send-keys -t $1:1.0 "tig" C-m
    tmux send-keys -t $1:1.1 "cd $2/$KATANA_REPO" C-m
    tmux send-keys -t $1:1.1 "clear" C-m
    # Editor window
    tmux new-window -n edit -t $1
    tmux send-keys -t $1:2 "cd $2/$KATANA_REPO" C-m
    tmux send-keys -t $1:2 "clear" C-m
    # Build window
    tmux new-window -n build -t $1
    tmux send-keys -t $1:3 "cd $2" C-m
    tmux send-keys -t $1:3 "clear" C-m
    # Run window
    tmux new-window -n run -t $1
    tmux send-keys -t $1:4 "cd $2/$KATANA_OBJECTS" C-m
    tmux send-keys -t $1:4 "clear" C-m
    # Go to console
    tmux select-window -t $1:0
}

if [[ $# = 0 ]]
then
    directory="."
else
    directory=$1
fi

directory=`realpath $directory`

if [[ ! -d $directory ]]
then
    echo $directory?
    exit
fi

session=`basename $directory | tr . _`
tmux has-session -t $session
if [ $? != 0 ]
then
    initTmux $session $directory
    setWindows $session $directory
fi

tmux attach -t $session
