#!/bin/env bash


SRC_DIR="app"


function initTmux {
	tmux new-session -s $1 -n console -d
	tmux send-keys -t $1 "cd $1" C-m
	tmux send-keys -t $1 "clear" C-m
}

function setWindows {
	# Vcs (git) window
	tmux new-window -n vcs -t $1
	tmux split-window -h -t $1:1
	tmux split-window -v -t $1:1.0
	tmux send-keys -t $1:1.0 "cd $1" C-m
	tmux send-keys -t $1:1.0 "git checkout develop" C-m
	tmux send-keys -t $1:1.0 "clear" C-m
	tmux send-keys -t $1:1.0 "git show-branch" C-m
	tmux send-keys -t $1:1.1 "cd $1" C-m
	tmux send-keys -t $1:1.1 "clear" C-m
	tmux send-keys -t $1:1.1 "tig --all" C-m
	tmux send-keys -t $1:1.2 "cd $1" C-m
	tmux send-keys -t $1:1.2 "clear" C-m
	# Editor window
	tmux new-window -n editor -t $1
	tmux send-keys -t $1:2 "cd $1/$SRC_DIR" C-m
	tmux send-keys -t $1:2 "clear" C-m
	# Server window
	tmux new-window -n server -t $1
	tmux send-keys -t $1:3 "cd $1" C-m
	tmux send-keys -t $1:3 "clear" C-m
	tmux send-keys -t $1:3 "./activator run" C-m
	# Play console window
	tmux new-window -n play -t $1
	tmux send-keys -t $1:4 "cd $1" C-m
	tmux send-keys -t $1:4 "clear" C-m
	tmux send-keys -t $1:4 "./activator" C-m
	# Go to console
	tmux select-window -t $1:0
}

if [[ $# = 0 ]]
then
	echo "game?"
	exit
fi

if [[ ! -d $1 ]]
then
	echo $1?
	exit
fi

tmux info &> /dev/null && tmux has-session -t $1
if [ $? != 0 ]
then
	initTmux $1
	setWindows $1
fi

tmux attach -t $1
