#!/bin/env bash

SESSION_NAME="psxle"
PSXLE_DIR="$1/psxle"
PCSXR_DIR="$1/PCSX-Reloaded/pcsxr"
PSXLE_SRC_DIR="$PSXLE_DIR/src"
PCSXR_CORE_DIR="$PCSXR_DIR/libpcsxcore"
PCSXR_PLUGINS_DIR="$PCSXR_DIR/plugins"
PCSXR_GUI_DIR="$PCSXR_DIR/gui"

function initTmux {
    tmux new-session -s $SESSION_NAME -n console -d
    tmux send-keys -t $SESSION_NAME "cd $PSXLE_DIR" C-m
    tmux send-keys -t $SESSION_NAME "clear" C-m
}

function setWindows {
    # Vcs (git) window
    tmux new-window -n git -t $SESSION_NAME
    tmux split-window -h -t $SESSION_NAME:1
    tmux split-window -v -t $SESSION_NAME:1.0
    tmux send-keys -t $SESSION_NAME:1.0 "cd $PSXLE_DIR" C-m
    tmux send-keys -t $SESSION_NAME:1.0 "git checkout develop" C-m
    tmux send-keys -t $SESSION_NAME:1.0 "clear" C-m
    tmux send-keys -t $SESSION_NAME:1.0 "git show-branch" C-m
    tmux send-keys -t $SESSION_NAME:1.1 "cd $PSXLE_DIR" C-m
    tmux send-keys -t $SESSION_NAME:1.1 "tig --all" C-m
    tmux send-keys -t $SESSION_NAME:1.2 "cd $PSXLE_DIR" C-m
    tmux send-keys -t $SESSION_NAME:1.2 "clear" C-m
    # Editor window
    tmux new-window -n edit -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:2 "cd $PSXLE_SRC_DIR" C-m
    tmux send-keys -t $SESSION_NAME:2 "clear" C-m
    # pcsxr core window
    tmux new-window -n core -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:3 "cd $PCSXR_CORE_DIR" C-m
    tmux send-keys -t $SESSION_NAME:3 "clear" C-m
    # pcsxr plugins window
    tmux new-window -n plugins -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:4 "cd $PCSXR_PLUGINS_DIR" C-m
    tmux send-keys -t $SESSION_NAME:4 "clear" C-m
    # pcsxr gui window
    tmux new-window -n gui -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:5 "cd $PCSXR_GUI_DIR" C-m
    tmux send-keys -t $SESSION_NAME:5 "clear" C-m
    # Go to console
    tmux select-window -t $SESSION_NAME:0
}

if [[ $# = 0 ]]
then
    echo "base dir?"
    exit
fi

if [[ ! -d $1 ]]
then
    echo $1?
    exit
fi

tmux info &> /dev/null && tmux has-session -t $SESSION_NAME
if [ $? != 0 ]
then
    initTmux
    setWindows
fi

tmux attach -t $SESSION_NAME
